#ifndef  __FR_NRAND_H__
#define  __FR_NRAND_H__

// These functions provide access to an implementation of the Fernandez-Rivero RNG as defined in http://www.springerlink.com/content/yj82465n0q755572/
// The functionality is not threadsafe. FIXME: Make the functionality threadsafe.

// Seeds the Fernandez-Rivero RNG with the given seed for the hash
// function and a standard deviation for the subsequent random numbers.
void snrand(unsigned int seed, double sd);

// Returns a normal distributed random number generated by the
// Fernandez-Rivero method with the standard deviation of the last seed.
double nrand();

// Returns a normal distributed random number generated by the
// Fernandez-Rivero method with the given standard deviation.
// This sets the standard deviation and can lead to a reset of the RNG.
double nrandsd(double sd);

#endif /* __FR_NRAND_H__*/
